### ISSUE TITLE
Tip ideas: accessibility

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [mine-cetinkaya-rundel/quarto-tip-a-day#12]
- [x] `fig-alt`
- [x] a11y-light and a11y-dark themes
- [x] slide tone
- [x] `aria-label`
- [x] `image-alt`

**Comment by batpigandme** [comment]
YAML options that should always be paired:

There are two main examples I can think of (both of which are now in "proper" form on the Quarto site):
1. When using icon in the menu (or footer for that matter), you should also use `aria-label` (e.g. https://github.com/quarto-dev/quarto-web/blob/0c615f26ae9a919d54650858fd5fd4bce51baa01/_quarto.yml#L40-L45)
2. When using image in page metadata (e.g. for a blog post), you should also use `image-alt` (e.g. https://github.com/quarto-dev/quarto-web/blob/0c615f26ae9a919d54650858fd5fd4bce51baa01/docs/blog/posts/2022-02-15-feature-tables/index.qmd#L12-L13)

**Comment by batpigandme** [comment]
Text for the `aria-label` one (feel free to change as needed…this was very awkward to word without just repeating "icon" over and over):

## `icon`s and `aria-label`s

For Quarto websites, you can `icon`s as [Nav Items](https://quarto.org/docs/reference/projects/websites.html#nav-items) in the [navbar](https://quarto.org/docs/reference/projects/websites.html#navbar) and/or [page footer](https://quarto.org/docs/reference/projects/websites.html#footer) YAML (the value can be the name of any of the [Bootstrap icons](https://icons.getbootstrap.com/)). To make these items accessible to screen readers, you should also add an `aria-label` describing what the navigation item is.

For example, here are snippets from the YAML for the Quarto documentation website. From the top navbar:

```yaml
website:
  navbar:
    right:
      - icon: twitter
        href: https://twitter.com/quarto_pub
        aria-label: Quarto Twitter
```

From the page footer:

```yaml
website:
  page-footer:
      - icon: github
        href: https://github.com/quarto-dev/quarto-cli
        aria-label: Quarto GitHub
```

## Learn more

[Nav items](https://quarto.org/docs/reference/projects/websites.html#nav-items).

**Comment by batpigandme** [comment]
Same caveats obviously apply for this one as well:

## `image-alt`

For Quarto websites, blog posts, and HTML pages, you can include an `image` in the metadata that will be displayed in places such as the thumbnail for blog posts (like each of the tips on this site), and the preview card on social media.

You can (and should) provide alt text for these images by using the `image-alt` option in your YAML as well. For example, here's a snippet from the YAML for the [tip on using dark mode](https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/17-dark-mode/).

```yaml
title: "Dark mode"
image: "featured.gif"
image-alt: "Switching between light and dark mode using the toggle on the navbar of this blog's homepage."
```

## Learn more

Note that `image-alt` can be supplied in several different places where an `image` can be specified, but that these will be inherited from the site or page metadata, so need not be repeated.

* [Website options](https://quarto.org/docs/reference/formats/html.html#website)

* [Twitter card options](https://quarto.org/docs/reference/projects/websites.html#twitter-card)

* [Open graph options](https://quarto.org/docs/reference/projects/websites.html#open-graph)
